### ISSUE TITLE
Light theme wanted

### ISSUE THREAD

**Issue by bouncepaw** [cblgh/lieu#1]
Hello, light theme is needed. I tried to fork and modify the project but had some problems (on my side, probably) related to sqlite. I don't want to deal with them currently, so I'm leaving the the task to you :-)

You probably need to add this to `base.css`:
```css
@media screen and (prefers-color-scheme: light) {
    :root {
        --primary: #000;
        --secondary: #fefefe;
    }
}
```

It will basically swap colors everywhere, except for the search button. You have hard-coded colors in the `logo.svg`, there are two ways to swap the colors:

1. Provide two versions of the file and serve them depending on current theme.
2. Change svg color with svg. Look [here](https://catalin.red/svg-favicon-light-dark-theme/#how-to-switch-the-svg-favicon-when-in-dark-mode) or somewhere else maybe.

Thanks
